# Generated by Django 5.2.9 on 2026-01-05 13:18

import django.core.validators
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text="Short catchy phrase (e.g., 'Building Faith, Changing Lives')", max_length=300)),
                ('welcome_message', models.TextField(help_text='Brief introduction for home page')),
                ('full_about', models.TextField(help_text='Complete church history and story for About page')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('core_values', models.TextField(blank=True, help_text='Core beliefs and values (optional)')),
                ('service_times_text', models.TextField(help_text='General service times description')),
                ('youtube_channel_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Information',
                'verbose_name_plural': 'Church Information',
            },
        ),
        migrations.CreateModel(
            name='GivingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flutterwave_link', models.URLField(help_text='Flutterwave payment page link')),
                ('title', models.CharField(default='Give Online', help_text='Page heading', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for donors (optional)')),
                ('why_give_message', models.TextField(blank=True, help_text='Optional: Biblical message about giving', null=True)),
                ('image_1', models.ImageField(blank=True, help_text='First image (e.g., Mobile Money QR code)', null=True, upload_to='giving/')),
                ('image_1_caption', models.CharField(blank=True, help_text='Description for image 1', max_length=200, null=True)),
                ('image_2', models.ImageField(blank=True, help_text='Second image (optional)', null=True, upload_to='giving/')),
                ('image_2_caption', models.CharField(blank=True, help_text='Description for image 2', max_length=200, null=True)),
                ('image_3', models.ImageField(blank=True, help_text='Third image (optional)', null=True, upload_to='giving/')),
                ('image_3_caption', models.CharField(blank=True, help_text='Description for image 3', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giving Page Content',
                'verbose_name_plural': 'Giving Page Content',
            },
        ),
        migrations.CreateModel(
            name='HeadPastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='Senior Pastor', help_text="Official title (e.g., 'Senior Pastor & Founder')", max_length=200)),
                ('full_bio', models.TextField(help_text='Complete biography')),
                ('image', models.ImageField(help_text='Professional photo (recommended: square format)', upload_to='leaders/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Head Pastor',
                'verbose_name_plural': 'Head Pastor',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('location', models.TextField(help_text='Full address for maps/GPS')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pastor_in_charge', models.CharField(help_text='Name of pastor leading this branch', max_length=200)),
                ('service_time', models.TextField(help_text="Service schedule (e.g., 'Sundays: 9AM & 11AM, Wednesdays: 6PM')")),
                ('image', models.ImageField(blank=True, help_text='Photo of the branch building/location', null=True, upload_to='branches/')),
                ('google_maps_url', models.URLField(blank=True, help_text='Google Maps link for directions', null=True)),
                ('is_main_branch', models.BooleanField(db_index=True, default=False, help_text='Check if this is the main/headquarters branch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Branch',
                'verbose_name_plural': 'Church Branches',
                'ordering': ['-is_main_branch', 'name'],
                'indexes': [models.Index(fields=['is_main_branch', 'name'], name='api_branch_is_main_dba7bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Prayer Request', 'Prayer Request'), ('Event Information', 'Event Information'), ('Service Information', 'Service Information'), ('Counseling Request', 'Counseling Request'), ('Partnership', 'Partnership/Collaboration'), ('Feedback', 'Feedback/Testimony'), ('Volunteer', 'Volunteer Opportunity'), ('Media Request', 'Media/Press Request'), ('Other', 'Other')], db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Mark as read after reviewing')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['is_read', '-submitted_at'], name='api_contact_is_read_965832_idx'), models.Index(fields=['subject', '-submitted_at'], name='api_contact_subject_a5e977_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Main heading text overlaid on banner', max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Subheading or description text', max_length=300, null=True)),
                ('image', models.ImageField(help_text='Banner image (recommended: 1920x600px)', upload_to='banners/%Y/%m/')),
                ('button_text', models.CharField(blank=True, help_text="Call-to-action button text (e.g., 'Join Us')", max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, help_text='Where the button should link to', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this banner')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='api_homeban_is_acti_ce4ae3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Associate Pastor', 'Associate Pastor'), ('Elder', 'Elder'), ('Deacon', 'Deacon'), ('Ministry Leader', 'Ministry Leader'), ('Worship Leader', 'Worship Leader'), ('Youth Pastor', 'Youth Pastor'), ("Children's Pastor", "Children's Pastor"), ('Other', 'Other')], help_text='Leadership role/title', max_length=100)),
                ('biography', models.TextField()),
                ('profile_picture', models.ImageField(help_text='Professional photo', upload_to='leaders/%Y/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_featured_on_home', models.BooleanField(db_index=True, default=False, help_text='Check to display on homepage', verbose_name='Feature on Home Page')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Church Leader',
                'verbose_name_plural': 'Church Leaders',
                'ordering': ['order', 'position', 'full_name'],
                'indexes': [models.Index(fields=['is_featured_on_home', 'order'], name='api_leader_is_feat_e35f8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Church photos', upload_to='gallery/%Y/%m/')),
                ('caption', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('category', models.CharField(choices=[('Church Building', 'Church Building'), ('Worship', 'Worship Service'), ('Events', 'Special Events'), ('Community', 'Community Life'), ('Youth', 'Youth Ministry'), ('Children', "Children's Ministry"), ('Outreach', 'Outreach & Missions'), ('Other', 'Other')], db_index=True, default='Other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photo Gallery',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category', '-uploaded_at'], name='api_photoga_categor_ee0903_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField()),
                ('speaker', models.CharField(db_index=True, help_text='Name of the preacher', max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True, help_text='Paste YouTube or Vimeo URL - thumbnails are generated automatically', null=True, verbose_name='Video Link (YouTube, Vimeo)')),
                ('custom_thumbnail', models.ImageField(blank=True, help_text='Optional: Upload custom thumbnail (overrides auto-generated)', null=True, upload_to='sermon_thumbnails/%Y/')),
                ('scripture_reference', models.CharField(blank=True, help_text="Bible passage reference (e.g., 'John 3:16-21')", max_length=200, null=True)),
                ('series', models.CharField(blank=True, db_index=True, help_text='Sermon series name (if part of a series)', max_length=200, null=True)),
                ('duration', models.CharField(blank=True, help_text="Video length (e.g., '45 min')", max_length=20, null=True)),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide drafts or archived sermons')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Feature on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sermon/Message',
                'verbose_name_plural': 'Sermons & Messages',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date', 'is_published'], name='api_sermon_date_3f6a70_idx'), models.Index(fields=['speaker', '-date'], name='api_sermon_speaker_57e807_idx'), models.Index(fields=['series', '-date'], name='api_sermon_series_9a982b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(db_index=True, help_text='Event date and start time')),
                ('location', models.CharField(help_text='Venue or address', max_length=300)),
                ('image', models.ImageField(help_text='Event poster or banner', upload_to='events/%Y/%m/')),
                ('category', models.CharField(choices=[('General', 'General Church Event'), ('Youth', 'Youth Event'), ('Women', "Women's Event"), ('Men', "Men's Event"), ('Children', "Children's Event"), ('Conference', 'Conference/Convention'), ('Outreach', 'Outreach/Evangelism'), ('Worship Night', 'Worship Night'), ('Prayer Meeting', 'Prayer Meeting'), ('Fundraiser', 'Fundraising Event'), ('Other', 'Other')], db_index=True, default='General', max_length=50)),
                ('registration_link', models.URLField(blank=True, help_text='External registration/ticketing link', null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Person to contact for questions', max_length=200, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide past events')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Feature on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Associated branch (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.branch')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='api_event_date_52d4be_idx'), models.Index(fields=['category', 'date'], name='api_event_categor_7f1a32_idx'), models.Index(fields=['is_featured', 'date'], name='api_event_is_feat_59a91c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_index=True, max_length=20)),
                ('time', models.CharField(help_text="e.g., '9:00 AM' or '6:00 PM'", max_length=50)),
                ('service_type', models.CharField(help_text="e.g., 'Sunday Worship', 'Midweek Service', 'Prayer Meeting'", max_length=200)),
                ('additional_info', models.CharField(blank=True, help_text="Extra details (e.g., 'With Holy Communion')", max_length=300, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for services at all branches', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_times', to='api.branch')),
            ],
            options={
                'verbose_name': 'Service Time',
                'verbose_name_plural': 'Service Times',
                'ordering': ['day', 'time'],
                'indexes': [models.Index(fields=['is_active', 'day'], name='api_service_is_acti_c6cb14_idx')],
            },
        ),
    ]
