# Generated by Django 5.2.9 on 2026-01-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givinginfo',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='givinginfo',
            name='image_1_caption',
        ),
        migrations.RemoveField(
            model_name='givinginfo',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='givinginfo',
            name='image_2_caption',
        ),
        migrations.RemoveField(
            model_name='givinginfo',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='givinginfo',
            name='image_3_caption',
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headpastor',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL (e.g., https://instagram.com/username)', null=True),
        ),
        migrations.AddField(
            model_name='headpastor',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp channel link (e.g., https://whatsapp.com/channel/...)', null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number (e.g., +1-555-0123)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('General', 'General Church Event'), ('Conference', 'Conference/Convention'), ('Outreach', 'Outreach/Evangelism'), ('Worship Night', 'Worship Night'), ('Healing to the city', 'Healing to the city'), ('Other', 'Other')], db_index=True, default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='headpastor',
            name='phone',
            field=models.CharField(blank=True, help_text="Pastor's office number (not personal number)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(choices=[('Shepherd', 'Shepherd'), ('Ministry Leader', 'Ministry Leader'), ('Worship Leader', 'Worship Leader'), ('Other', 'Other')], help_text='Leadership role/title', max_length=100),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.CharField(choices=[('Church Building', 'Church Building'), ('Worship', 'Worship Service'), ('Events', 'Special Events'), ('Community', 'Community Life'), ('Outreach', 'Outreach & Missions'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='GivingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='QR code, bank details, payment instruction, etc.', upload_to='giving/')),
                ('caption', models.CharField(blank=True, help_text="Description for this image (e.g., 'Mobile Money QR Code')", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giving_info', models.ForeignKey(help_text='Link to the main giving page', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.givinginfo')),
            ],
            options={
                'verbose_name': 'Giving Page Image',
                'verbose_name_plural': 'Giving Page Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_log/')),
                ('object_id', models.PositiveIntegerField()),
                ('section_name', models.CharField(help_text='Which section this image is from (Banner, Pastor, Leader, etc.)', max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Image file size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Image Log',
                'verbose_name_plural': 'Image Logs',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['section_name', '-uploaded_at'], name='api_imagelo_section_362ead_idx'), models.Index(fields=['content_type', 'object_id'], name='api_imagelo_content_ad9926_idx')],
            },
        ),
    ]
