# Generated by Django 5.2.9 on 2026-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_givinginfo_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='views',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.CharField(choices=[('Church Building', 'Church Building'), ('Worship', 'Worship Service'), ('Events', 'Special Events'), ('Outreach', 'Outreach & Missions'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
    ]
