# Generated by Django 5.2.8 on 2026-01-14 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testimony_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimony Archive'},
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='api_contact_show_on_227de4_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='api_contact_is_appr_06605d_idx',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='show_on_carousel',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='source_message',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testimony',
            name='category',
            field=models.CharField(blank=True, help_text='Optional: Healing, Salvation, Financial, etc. (for book organization)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimony',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='✓ Verified and approved (for book/records)'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimony',
            name='show_on_carousel',
            field=models.BooleanField(db_index=True, default=False, help_text='✓ Display on home page carousel'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony', to='api.contactmessage'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', '-submitted_at'], name='api_contact_is_read_965832_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['subject', '-submitted_at'], name='api_contact_subject_a5e977_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['show_on_carousel', 'order'], name='api_testimo_show_on_e03789_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['is_approved', 'category'], name='api_testimo_is_appr_b96105_idx'),
        ),
    ]
