# Generated by Django 5.2.8 on 2026-01-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contactmessage_options_alter_testimony_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book title', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in currency', max_digits=10)),
                ('image', models.ImageField(help_text='Book cover image', upload_to='books/')),
                ('description', models.TextField(blank=True, help_text='Book description or summary', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='WhatsApp chat link to purchase (e.g., https://wa.me/...)', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email to contact for purchase', max_length=254, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_available', '-created_at'], name='api_book_is_avai_08c9b0_idx')],
            },
        ),
    ]
