# Generated by Django 5.2.8 on 2026-01-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchinfo',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headpastor',
            name='tiktok',
            field=models.URLField(blank=True, help_text='TikTok profile URL (e.g., https://tiktok.com/@username)', null=True),
        ),
    ]
