# Generated by Django 5.2.8 on 2026-01-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_churchinfo_tiktok_url_headpastor_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon',
            field=models.URLField(blank=True, help_text='Amazon purchase link', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in dollars (e.g., 19.99)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(db_index=True, help_text='ISO currency code (e.g., USD, GHS, CUP, GBP)', max_length=3, unique=True)),
                ('currency_name', models.CharField(blank=True, help_text='Currency name (e.g., US Dollar, Ghana Cedi)', max_length=100)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from USD (e.g., 0.5 means 1 USD = 0.5 of this currency)', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency_code'],
                'indexes': [models.Index(fields=['currency_code'], name='api_exchang_currenc_e94b1f_idx'), models.Index(fields=['-last_updated'], name='api_exchang_last_up_7f9a66_idx')],
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Merchandise name (e.g., 'TGA Church Hoodie')", max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('image', models.ImageField(help_text='Product image/photo', upload_to='merchandise/')),
                ('description', models.TextField(blank=True, help_text='Product description, colors, sizes, materials, etc. (optional)', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='WhatsApp chat link to purchase (e.g., https://wa.me/...)', null=True)),
                ('jiji_link', models.URLField(blank=True, help_text='Jiji marketplace link to purchase', null=True)),
                ('amazon_link', models.URLField(blank=True, help_text='Amazon purchase link', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email to contact for purchase', max_length=254, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchandise',
                'verbose_name_plural': 'Merchandise',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_available', '-created_at'], name='api_merchan_is_avai_80d797_idx')],
            },
        ),
    ]
