# Generated by Django 5.2.8 on 2026-04-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='button_text',
        ),
    ]
