# Generated by Django 5.2.8 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_homebanner_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headpastor',
            name='website',
            field=models.URLField(blank=True, help_text='Personal website URL (e.g., https://pastorname.com)', null=True),
        ),
    ]
