# Generated by Django 5.2.8 on 2026-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_branch_email_alter_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
