# Generated by Django 5.2.8 on 2026-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_churchinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchinfo',
            name='phone',
            field=models.TextField(blank=True, help_text='Phone number(s) separated by commas or new lines', null=True),
        ),
    ]
