# Generated by Django 5.2.8 on 2026-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_churchinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes (e.g. S, M, L, XL, XXL). Only used if Has Sizes is checked.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='has_sizes',
            field=models.BooleanField(default=False, help_text='Check if this item comes in different sizes (e.g. shirts, hoodies)'),
        ),
        migrations.AlterField(
            model_name='servicetime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday-Friday', 'Monday - Friday'), ('Wednesday-Friday', 'Wednesday - Friday')], db_index=True, max_length=20),
        ),
    ]
