# Generated by Django 5.2.8 on 2026-09-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_backfill_country_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_satellite',
            field=models.BooleanField(db_index=True, default=False, help_text="No physical building — meets online only via the church's YouTube/TikTok"),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.TextField(blank=True, help_text='Full address for maps/GPS — leave blank for a satellite (online-only) branch'),
        ),
    ]
