# Generated by Django 5.2.8 on 2026-09-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_branch_is_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='api.country'),
        ),
    ]
